### ISSUE TITLE
UI scaling issues

### ISSUE THREAD

**Issue by TorecLuik** [Cellular-Imaging-Amsterdam-UMC/NL-BIOMERO#4]
![image](https://github.com/Cellular-Imaging-Amsterdam-UMC/NL-BIOMERO/assets/68958516/4a4e48cb-ce92-40f4-9adb-010f3014a17b)

UI scaling issues detected on latest release (0.4) with your new buttons / functionality, see screenshot.

**Comment by rodrigolearns** [comment]
Donzo #[1b7136c](https://github.com/Cellular-Imaging-Amsterdam-UMC/NL-BIOMERO/commit/1b7136c9acab4ac37e4cb473cb1ed4543b178ea1)

**Comment by rodrigolearns** [comment]
Donzo #[1b7136c](https://github.com/Cellular-Imaging-Amsterdam-UMC/NL-BIOMERO/commit/1b7136c9acab4ac37e4cb473cb1ed4543b178ea1)
